AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sam template for News-sam-app.
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
  Api:
    Cors:
      AllowMethods: "'DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"

Resources:
  GetNewsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: get_news/
      AutoPublishAlias: live
      Handler: get_news.lambdaHandlerGetList
      Runtime: nodejs10.x
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref NewsTable
      Events:
        GetNews:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /getnews
            Method: get
        GetNewsProxy:
          Type: Api
          Properties:
            Path: /getnews/{proxy+}
            Method: get

  PostNewsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: post_news/
      AutoPublishAlias: live
      Handler: post_news.lambdaSubmit
      Runtime: nodejs10.x
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref NewsTable
      Events:
        PostNews:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /postnews
            Method: post
        PostNewsProxy:
          Type: Api
          Properties:
            Path: /postnews/{proxy+}
            Method: post
  
  NewsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: news_app_table
      AttributeDefinitions:
        - AttributeName: news_date
          AttributeType: S
        - AttributeName: news_title
          AttributeType: S
      KeySchema:
        - AttributeName: news_date
          KeyType: HASH
        - AttributeName: news_title
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GetNewsApi:
    Description: "API Gateway endpoint URL for Prod stage for Get News function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/getnews/"
  GetNewsFunction:
    Description: "Get News Lambda Function ARN"
    Value: !GetAtt GetNewsFunction.Arn
  GetNewsFunctionIamRole:
    Description: "Implicit IAM Role created for Get News function"
    Value: !GetAtt GetNewsFunctionRole.Arn 
  PostNewsApi:
    Description: "API Gateway endpoint URL for Prod stage for Post News function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/postnews/"
  PostNewsFunction:
    Description: "Post News Lambda Function ARN"
    Value: !GetAtt PostNewsFunction.Arn
  GetNewsFunctionIamRole:
    Description: "Implicit IAM Role created for Post News function"
    Value: !GetAtt PostNewsFunctionRole.Arn 